/*
Copyright © 2023 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
Code generated by go-swagger; DO NOT EDIT.
*/

package policyrecipenetworkmodel

import "github.com/go-openapi/swag"

// VmwareTanzuManageV1alpha1CommonPolicySpecNetworkV1AllowAllToPods allow-all-to-pods schema
//
// swagger:model VmwareTanzuManageV1alpha1CommonPolicySpecNetworkV1AllowAllToPods
type VmwareTanzuManageV1alpha1CommonPolicySpecNetworkV1AllowAllToPods struct {

	// Allow traffic only from own namespace
	// Allow traffic only from pods in the same namespace as the destination pod. Defaults to false (allow from all namespaces).
	FromOwnNamespace *bool `json:"fromOwnNamespace,omitempty"`

	// Pod Labels on which traffic should be allowed
	// Use a label selector to identify the pods to which the policy applies
	// Required: true
	ToPodLabels []*VmwareTanzuManageV1alpha1CommonPolicySpecNetworkV1AllowAllToPodsToPodLabels `json:"toPodLabels"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1CommonPolicySpecNetworkV1AllowAllToPods) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1CommonPolicySpecNetworkV1AllowAllToPods) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1CommonPolicySpecNetworkV1AllowAllToPods
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}

// VmwareTanzuManageV1alpha1CommonPolicySpecNetworkV1AllowAllToPodsToPodLabels Label Key-Value Pair
//
// swagger:model VmwareTanzuManageV1alpha1CommonPolicySpecNetworkV1AllowAllToPodsToPodLabels
type VmwareTanzuManageV1alpha1CommonPolicySpecNetworkV1AllowAllToPodsToPodLabels struct {

	// Label Key
	// Required: true
	// Max Length: 316
	// Pattern: ^([[:alnum:]][[:alnum:]-]*[[:alnum:]](.[[:alnum:]][[:alnum:]-]*[[:alnum:]])*/)?[[:alnum:]][[:alnum:]._-]{0,61}[[:alnum:]]$
	Key *string `json:"key"`

	// Label Value
	// Required: true
	// Max Length: 63
	// Pattern: ^([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$
	Value *string `json:"value"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1CommonPolicySpecNetworkV1AllowAllToPodsToPodLabels) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1CommonPolicySpecNetworkV1AllowAllToPodsToPodLabels) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1CommonPolicySpecNetworkV1AllowAllToPodsToPodLabels
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}
